[package]
name = "aya-tool"
version = "0.1.0"
authors = ["Alessandro Decina <alessandro.d@gmail.com>"]
edition = "2021"

[dependencies]
bindgen = "0.61"
clap = { version = "3", features = ["derive"] }
anyhow = "1"
thiserror = "1"
tempfile = "3"
