[package]
name = "aya-log-parser"
version = "0.1.13"
description = "A parser for the aya log format strings"
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
edition.workspace = true

[dependencies]
aya-log-common = { path = "../aya-log-common", version = "^0.1.14", default-features = false }

[lib]
path = "src/lib.rs"
