[package]
name = "xtask"
version = "0.1.0"
authors = ["Alessandro Decina <alessandro.d@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1"
aya-tool = { path = "../aya-tool" }
cargo_metadata = "0.15.4"
clap = { version = "4", features = ["derive"] }
indoc = "2.0"
proc-macro2 = "1"
quote = "1"
syn = "2"
tempfile = "3"
