[package]
name = "xtask"
version = "0.1.0"
authors = ["Alessandro Decina <alessandro.d@gmail.com>"]
edition = "2021"

[dependencies]
aya-tool = { path = "../aya-tool" }
clap = { version = "3", features = ["derive"] }
anyhow = "1"
syn = "1"
quote = "1"
proc-macro2 = "1"
indoc = "1.0"
lazy_static = "1"
serde_json = "1"