[package]
name = "aya-log-common"
version = "0.1.13"
description = "A logging library for eBPF programs."
keywords = ["ebpf", "bpf", "log", "logging"]
license = "MIT OR Apache-2.0"
authors = ["The Aya Contributors"]
repository = "https://github.com/aya-rs/aya-log"
documentation = "https://docs.rs/aya-log"
edition = "2021"

[dependencies]
num_enum = { version = "0.6", default-features = false }

[lib]
path = "src/lib.rs"
