[package]
description = "Bindings for Linux Kernel eBPF types and helpers"
name = "aya-ebpf-bindings"
version = "0.1.2"

authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
aya = { path = "../../aya", version = "^0.13.1", optional = true }
aya-ebpf-cty = { version = "^0.2.3", path = "../aya-ebpf-cty" }

[build-dependencies]
aya-build = { version = "^0.1.3", path = "../../aya-build" }

[features]
user = ["dep:aya"]
