[package]
description = "A library for writing eBPF programs"
name = "aya-ebpf"
version = "0.1.1"

authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
aya-ebpf-bindings = { version = "^0.1.1", path = "../aya-ebpf-bindings" }
aya-ebpf-cty = { version = "^0.2.2", path = "../aya-ebpf-cty" }
aya-ebpf-macros = { version = "^0.1.1", path = "../../aya-ebpf-macros" }

[build-dependencies]
rustversion = { workspace = true }

[features]
btf-maps = ["aya-ebpf-macros/btf-maps"]
default = ["btf-maps"]
