[package]
name = "aya-ebpf"
version = "0.1.1"
description = "A library for writing eBPF programs"
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
edition.workspace = true

[dependencies]
aya-ebpf-macros = { version = "^0.1.1", path = "../../aya-ebpf-macros" }
aya-ebpf-bindings = { version = "^0.1.1", path = "../aya-ebpf-bindings" }

[build-dependencies]
rustversion = { workspace = true }
