[package]
name = "aya-log"
version = "0.1.13"
description = "A logging library for eBPF programs."
keywords = ["bpf", "ebpf", "log", "logging"]
license = "MIT OR Apache-2.0"
authors = ["The Aya Contributors"]
repository = "https://github.com/aya-rs/aya-log"
readme = "README.md"
documentation = "https://docs.rs/aya-log"
edition = "2021"

[dependencies]
aya = { workspace = true }
aya-log-common = { workspace = true }
bytes = { workspace = true }
log = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt"] }

[dev-dependencies]
env_logger = { workspace = true }
testing_logger = { workspace = true }

[lib]
path = "src/lib.rs"
