[package]
description = "XDP dispatcher for eBPF programs"
name = "aya-xdp-dispatcher-ebpf"
version = "0.1.0"

authors = ["Aya Contributors", "Authors of bpfd"]
edition.workspace = true
homepage.workspace = true
license = "GPL-2.0-only OR BSD-2-Clause"
repository.workspace = true
rust-version.workspace = true

[target.'cfg(target_arch = "bpf")'.dependencies]
aya-ebpf = { version = "^0.1.2", path = "../aya-ebpf" }

[target.'cfg(not(target_arch = "bpf"))'.dependencies]
aya = { version = "^0.13.2", path = "../../aya" }
bytemuck = { workspace = true, features = ["derive"] }

[build-dependencies]
which = { workspace = true, features = ["real-sys"] }
