name: build-aya

on:
  push:
    branches:
      - main
      - ci

  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        arch:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
          - armv7-unknown-linux-gnueabi
          - riscv64gc-unknown-none-elf
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - name: Prereqs
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Build
        run: cross build --verbose

      - name: Run test
        run: RUST_BACKTRACE=full cross test --verbose

      - name: Build bpf macros
        run: cross build --manifest-path ./bpf/Cargo.toml -p aya-bpf-macros --verbose

      - name: Test bpf macros
        run: RUST_BACKTRACE=full cross test --manifest-path ./bpf/Cargo.toml -p aya-bpf-macros --verbose

  test:
    runs-on: ubuntu-20.04
    needs: build
    container:
      image: ghcr.io/aya-rs/aya-test-rtf:main

    steps:
      - uses: actions/checkout@v2

      - name: Run regression tests
        run: |
          ln -s /root/.rustup ${HOME}/.rustup
          cd test
          rtf -vvv run
